<template>
<section class="">
    <!-- Header -->
    <div class="header d-flex align-items-center">
      <h5 class="m-0">Olopo Privacy Policy</h5>
    </div>

    <!-- Content -->
    <div class="container mt-4">

      <h6 class="section-title">Introduction</h6>
      <p>This Privacy Policy explains our policies and procedures regarding the collection, use, and disclosure of your information when you use our Service. It informs you about your privacy rights and how the law protects you. By using the Service, you agree to the collection and use of information as described in this Privacy Policy.</p>

      <h6 class="section-title">Interpretation and Definitions</h6>

      <h6 class="section-title">Interpretation</h6>
      <p>Words with the initial letter capitalized have meanings defined below. These definitions have the same meaning whether they appear in singular or plural form.</p>

      <h6 class="section-title">Definitions</h6>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li><strong>Merchant</strong> - A person or company involved in wholesale trade, particularly one dealing with foreign countries or supplying goods to a specific trade.</li>
        <li><strong>Account</strong> - A unique account created for you to access our Service or parts of our Service.</li>
        <li><strong>Business</strong> - Refers to the Company as the legal entity that collects consumers' personal information and determines the purposes and means of processing this information, or on behalf of which such information is collected. This entity operates in India.</li>
        <li><strong>Company</strong> - Referred to as "the Company," "We," "Us," or "Our" in this Agreement. The Company is the Data Controller for the purpose of this Privacy Policy.</li>
        <li><strong>Country</strong> - Refers to India and may include international countries.</li>
        <li><strong>Consumer</strong> - Any person who buys a product or hires/avails of a service for consideration as per the Consumer Protection Act, 1986. It includes any user of such goods or beneficiary of such services provided with the buyer's approval.</li>
        <li><strong>Personal Data</strong> - Any information relating to an identified or identifiable individual.</li>
        <li><strong>Service</strong> - Refers to the services provided by our mobile application.</li>
        <li><strong>Service Provider</strong> - Any individual, private agency, company, partnership, sole proprietorship, or other body authorized by the appropriate Government to offer services through electronic means.</li>
        <li><strong>Usage Data</strong> - Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        <li><strong>Website</strong> - Refers to aspiromtechnologies.com</li>
        <li><strong>You</strong> - The individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service.</li>
      </ul>

      <h6 class="section-title">Collecting and Using Your Personal Data</h6>

      <h6 class="section-title">Types of Data Collected</h6>

      <h6 class="section-title">Personal Data</h6>
      <p>While using our Service, we may ask you to provide certain personally identifiable information, which may include, but is not limited to:</p>
      <ul>
        <li>Company Name</li>
        <li>Email address</li>
        <li>GST Details</li>
        <li>PAN Card Details</li>
        <li>Bank Account details</li>
        <li>Phone number</li>
        <li>Address, State, Postal code, City</li>
      </ul>

      <h6 class="section-title">Usage Data</h6>
      <p>Usage Data is collected automatically when using the Service. This may include information such as your device's IP address, browser type, browser version, pages of our Service you visit, time and date of your visit, time spent on those pages, unique device identifiers, and other diagnostic data. When accessing the Service via a mobile device, we may collect information such as the location of your device, contacts, gallery, relevant applications, device type, unique device ID, IP address, mobile operating system, and browser type.</p>

      <h6 class="section-title">API Based Tokens for Secure User Authentication</h6>
      <ul>
        <li>Authentication establishes the identity of the user and verifies that the user is who (or what) it says it is. Authentication protects your resources by denying access to unauthenticated users.</li>
        <li>Authentication gives each user a distinct identity, protecting your data and theirs. Applications that require users to create an account give each user a unique profile, which is what determines the data shown to the user. For example, PayPal requires users to sign in before displaying their account balance and transactions.</li>
      </ul>

      <h6 class="section-title">Use of Your Personal Data</h6>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li><strong>To provide and maintain our Service:</strong> Including monitoring the usage of our Service.</li>
        <li><strong>To manage your account:</strong> To manage your registration as a merchant of the Service and provide access to various functionalities available to registered users.</li>
        <li><strong>To contact you:</strong> By email, telephone calls, SMS, or other forms of electronic communication.</li>
        <li><strong>To provide you with news and offers:</strong> Regarding our services and events, similar to those you have already purchased or enquired about unless you opt out.</li>
        <li><strong>To manage your requests:</strong> To attend and manage requests made by you.</li>
        <li><strong>For other purposes:</strong> Such as data analysis, identifying usage trends, evaluating promotional campaigns, and improving our Service, products, services, marketing, and consumer experience.</li>
      </ul>

      <h6 class="section-title">Sharing Your Personal Information</h6>
      <p>We may share your personal information with:</p>
      <ul>
        <li>Service Providers</li>
        <li>Payment processors</li>
        <li>Our affiliates</li>
        <li>Our business partners</li>
        <li>Third-party vendors authorized by you or your agents in connection with products or services we provide to you.</li>
      </ul>

      <h6 class="section-title">Requests and Verification</h6>
      <p>To request clarification or information, you must:</p>
      <ul>
        <li>Provide sufficient information to verify your identity and authority.</li>
        <li>Describe your request in sufficient detail to allow us to understand, evaluate, and respond.</li>
      </ul>
      <p>We will disclose and deliver the requested information free of charge within 45 days of receiving your verifiable request, extendable by an additional 45 days with prior notice if necessary.</p>

      <h6 class="section-title">Transfer of Your Personal Data</h6>
      <p>Your data, including personal information, is processed at the Company's offices and other locations involved in the process. This means your data might be transferred to and stored on computers outside your state, province, or country, where data protection laws might be different.</p>
      <p>By agreeing to this Privacy Policy and providing your information, you consent to this transfer.</p>
      <p>The Company will take all reasonable steps to ensure your data is handled securely and according to this Privacy Policy. No data transfer will occur unless the receiving organization or country has adequate data protection measures in place.</p>

      <h6 class="section-title">Disclosure of Your Personal Data</h6>

      <h6 class="section-title">Business Transactions</h6>
      <p>If the Company is involved in a merger, acquisition, or sale of assets, your personal data may be transferred. We will notify you before your data is transferred and becomes subject to a different Privacy Policy.</p>

      <h6 class="section-title">Law Enforcement</h6>
      <p>The Company may disclose your personal data if required by law or in response to valid requests from public authorities (e.g., a court or government agency).</p>

      <h6 class="section-title">Other Legal Requirements</h6>
      <p>The Company may disclose your personal data if it believes in good faith that such action is necessary to:</p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the Company's rights or property</li>
        <li>Prevent or investigate possible wrongdoing related to the service</li>
        <li>Protect the personal safety of service users or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h6 class="section-title">Security of Your Personal Data</h6>
      <p>The security of your personal data is important to us, but no method of internet transmission or electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your data, we cannot guarantee absolute security.</p>

      <h6 class="section-title">Detailed Information on the Processing of Your Personal Data</h6>
      <p>Our service providers may access your personal data. These third-party vendors collect, store, use, process, and transfer information about your activity on our service according to their privacy policies.</p>

      <h6 class="section-title">Analytics</h6>
      <p>We may use third-party service providers to monitor and analyse the use of our service.</p>

      <h6 class="section-title">Email Marketing</h6>
      <p>We may use your personal data to contact you with newsletters, marketing, promotional materials, and other information of interest. You can opt out of these communications by following the unsubscribe link or instructions in any email we send or by contacting us.</p>

      <h6 class="section-title">Payments</h6>
      <p>We may offer paid products and services. In such cases, we use third-party payment processors. We do not store or collect your payment card details; this information is provided directly to our payment processors, whose use of your personal information is governed by their privacy policies.</p>

      <h6 class="section-title">Legal Basis for Processing Personal Data</h6>
      <p>We may process your personal data under these conditions:</p>
      <ul>
        <li><strong>Consent:</strong> You have given us permission to process your data for specific reasons.</li>
        <li><strong>Performance of a contract:</strong> We need your data to fulfill a contract or pre-contractual obligations.</li>
        <li><strong>Legal obligations:</strong> We need to process your data to comply with the law.</li>
        <li><strong>Vital interests:</strong> We need to process your data to protect your vital interests or those of another person.</li>
        <li><strong>Public interests:</strong> We process your data for tasks in the public interest or official authority.</li>
        <li><strong>Legitimate interests:</strong> We process your data for our legitimate business interests.</li>
      </ul>
      <p>We can explain the specific legal basis for processing your data and whether providing your data is legally or contractually required.</p>

      <h6 class="section-title">Your Rights</h6>
      <p>We respect your privacy and rights regarding your personal data.</p>
      <ul>
        <li><strong>Access your data:</strong> You can access, update, or delete your data in your account settings or by contacting us.</li>
        <li><strong>Correct your data:</strong> You can ask us to correct any incomplete or inaccurate information.</li>
        <li><strong>Object to processing:</strong> You can object to our processing of your data if it affects you.</li>
        <li><strong>Request erasure:</strong> You can ask us to delete your data if there is no reason for us to keep it.</li>
        <li><strong>Request data transfer:</strong> We can provide your data in a machine-readable format to you or a third party.</li>
        <li><strong>Withdraw consent:</strong> You can withdraw your consent for us to use your data, though this may limit certain services we provide.</li>
      </ul>

      <h6 class="section-title">Do Not Share My Personal Information</h6>
      <p>Upon receiving a verifiable merchant request, we will not share your information with third parties without consent. To exercise your rights, we may need to verify your identity. We will respond as quickly as possible.</p>
      <p>If you have any privacy concerns, please contact us.</p>

      <h6 class="section-title">Changes to This Privacy Policy</h6>
      <p>We may update our Privacy Policy from time to time. Changes will be posted on this page, and we will notify you via email and/or a prominent notice on our Service prior to the changes becoming effective. You are advised to review this Privacy Policy periodically.</p>

      <h6 class="section-title">Contact Us</h6>
      <p>If you have any questions about this Privacy Policy, you can contact us:</p>
      <ul>
        <li>By visiting this page on our website: <a href="https://aspiromtechnologies.com" target="_blank">aspiromtechnologies.com</a></li>
        <li>By sending us an email: <a href="mailto:info@olopo.app">info@olopo.app</a></li>
      </ul>
    </div>
  </section>
</template>
<script>
export default {
    name: "Privacy",
    mounted() {
    }
}
</script>
